/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.Query;
import Model.Cobertura;
import static com.itextpdf.kernel.pdf.PdfName.Document;
import com.itextpdf.kernel.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

/**
 *
 * @author mauri
 */
public class CadastroCobertura extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCobertura
     */
    public CadastroCobertura() {
        
        initComponents();
        setMask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dadosPessoais = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        end = new javax.swing.JTextField();
        endNum = new javax.swing.JTextField();
        cidadeNat = new javax.swing.JTextField();
        nmMae = new javax.swing.JTextField();
        bairro = new javax.swing.JTextField();
        nmPai = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        fone = new javax.swing.JFormattedTextField();
        celular = new javax.swing.JFormattedTextField();
        dtNasc = new javax.swing.JFormattedTextField();
        cep = new javax.swing.JFormattedTextField();
        documentos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        ctps = new javax.swing.JTextField();
        pis = new javax.swing.JTextField();
        rg = new javax.swing.JTextField();
        serie = new javax.swing.JTextField();
        uf = new javax.swing.JTextField();
        dt = new javax.swing.JFormattedTextField();
        dtPis = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        conta = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cp = new javax.swing.JCheckBox();
        cc = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        agencia = new javax.swing.JTextField();
        digito = new javax.swing.JTextField();
        numCC = new javax.swing.JTextField();
        numCP = new javax.swing.JTextField();
        tipoConta = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        cadCob = new javax.swing.JButton();
        limpDados = new javax.swing.JButton();
        btFichas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 710));

        jLabel1.setText("Nome completo:");

        jLabel2.setText("Endereço:");

        jLabel4.setText("Bairro/Vila:");

        jLabel5.setText("Cidade:");

        jLabel6.setText("CEP");

        jLabel3.setText("Nº");

        jLabel7.setText("Cidade Nat:");

        jLabel8.setText("Fone:");

        jLabel9.setText("Celular:");

        jLabel10.setText("Data de Nascimento:");

        jLabel11.setText("Nome da Mãe");

        jLabel12.setText("Nome do Pai:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel25.setText("Dados Pessoais");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dadosPessoaisLayout = new javax.swing.GroupLayout(dadosPessoais);
        dadosPessoais.setLayout(dadosPessoaisLayout);
        dadosPessoaisLayout.setHorizontalGroup(
            dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPessoaisLayout.createSequentialGroup()
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosPessoaisLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGap(33, 33, 33)
                        .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadosPessoaisLayout.createSequentialGroup()
                                .addComponent(nmPai, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel11)
                                .addGap(27, 27, 27)
                                .addComponent(nmMae, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dadosPessoaisLayout.createSequentialGroup()
                                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bairro, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                    .addComponent(fone))
                                .addGap(44, 44, 44)
                                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(celular))
                                .addGap(20, 20, 20)
                                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(27, 27, 27)
                                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(dadosPessoaisLayout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cidadeNat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(dadosPessoaisLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(endNum, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(end, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
                                .addComponent(nome))))
                    .addGroup(dadosPessoaisLayout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dadosPessoaisLayout.setVerticalGroup(
            dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPessoaisLayout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(26, 26, 26)
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cidadeNat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(nmMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("CPF:");

        jLabel14.setText("RG:");

        jLabel15.setText("CTPS:");

        jLabel16.setText("Serie:");

        jLabel17.setText("UF:");

        jLabel18.setText("DT:");

        jLabel19.setText("PIS:");

        jLabel20.setText("DT:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel24.setText("Documentação");

        javax.swing.GroupLayout documentosLayout = new javax.swing.GroupLayout(documentos);
        documentos.setLayout(documentosLayout);
        documentosLayout.setHorizontalGroup(
            documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(documentosLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addGap(33, 33, 33)
                .addGroup(documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(documentosLayout.createSequentialGroup()
                        .addGroup(documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(documentosLayout.createSequentialGroup()
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)))
                            .addComponent(ctps, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(documentosLayout.createSequentialGroup()
                                .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(298, 298, 298))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, documentosLayout.createSequentialGroup()
                                .addComponent(serie, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))))
                    .addGroup(documentosLayout.createSequentialGroup()
                        .addComponent(pis, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(dtPis, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(420, 420, 420))))
            .addGroup(documentosLayout.createSequentialGroup()
                .addGap(523, 523, 523)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        documentosLayout.setVerticalGroup(
            documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(documentosLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(ctps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(pis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtPis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel21.setText("Agencia:");

        jLabel22.setText("Digito:");

        cp.setText("Nº Conta Poupança:");
        cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpActionPerformed(evt);
            }
        });

        cc.setText("Nº Conta Corrente:");
        cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel23.setText("Dados da Conta");

        tipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco do Brasil", "Bradesco", "Caixa Economica" }));
        tipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contaLayout = new javax.swing.GroupLayout(conta);
        conta.setLayout(contaLayout);
        contaLayout.setHorizontalGroup(
            contaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel21)
                .addGap(36, 36, 36)
                .addComponent(agencia, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(digito, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(contaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cc)
                    .addComponent(cp))
                .addGap(18, 18, 18)
                .addGroup(contaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numCC)
                    .addComponent(numCP, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(776, 776, 776))
            .addGroup(contaLayout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contaLayout.setVerticalGroup(
            contaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(12, 12, 12)
                .addGroup(contaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(contaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(digito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contaLayout.createSequentialGroup()
                        .addGroup(contaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cc)
                            .addComponent(numCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cp)
                            .addComponent(numCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cadCob.setText("Cadastrar Cobertura");
        cadCob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCobActionPerformed(evt);
            }
        });

        limpDados.setText("Limpar Dados");
        limpDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpDadosActionPerformed(evt);
            }
        });

        btFichas.setText("Fichas Completas");
        btFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFichasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(cadCob)
                .addGap(65, 65, 65)
                .addComponent(limpDados)
                .addGap(56, 56, 56)
                .addComponent(btFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCob, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpDados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(conta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 1289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccActionPerformed

    private void cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cadCobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCobActionPerformed
        // TODO add your handling code here:
        
        
        Cobertura d = new Cobertura();
         Query dao = new Query();
        
        
        if(nome.getText().isEmpty()){
            
            
        }else{
            d.setNome(nome.getText());
        }
        
        if(end.getText().isEmpty()){
              d.setEndereco("Não Preenchido");
        }else{
            d.setEndereco(end.getText());
        }
        
        if(endNum.getText().isEmpty()){
              d.setNumero("Não Preenchido");
        }else{
            d.setNumero(endNum.getText());
        }
        
        if(bairro.getText().isEmpty()){
              d.setBairro("Não Preenchido");
        }else{
            d.setBairro(bairro.getText());
        }
        
        if(cidade.getText().isEmpty()){
              d.setCidade("Não Preenchido");
        }else{
            d.setCidade(cidade.getText());
        }
        
        
        if(cep.getText().isEmpty()){
              d.setCep("Não Preenchido");
        }else{
            d.setCep(cep.getText());
        }
        
        if(cidadeNat.getText().isEmpty()){
              d.setCidade_nat("Não Preenchido");
        }else{
            d.setCidade_nat(cidadeNat.getText());
        }
        
        if(fone.getText().isEmpty()){
              d.setTelefone("Não Preenchido");
        }else{
             d.setTelefone(fone.getText());
        }
        
        if(celular.getText().isEmpty()){
              d.setCelular("Não Preenchido");
        }else{
             d.setCelular(celular.getText());
        }
        
        if(dtNasc.getText().isEmpty()){
              d.setData_nascimento("Não Preenchido");
        }else{
             d.setData_nascimento(dtNasc.getText());
        }
        
        if(nmPai.getText().isEmpty()){
              d.setPai("Não Preenchido");
        }else{
             d.setPai(nmPai.getText());
        }
        
        if(nmMae.getText().isEmpty()){
              d.setMae("Não Preenchido");
        }else{
              d.setMae(nmMae.getText());
        }
        
        if(cpf.getText().isEmpty()){
              d.setCpf("Não Preenchido");
        }else{
              d.setCpf(cpf.getText());
        }
       
        if(rg.getText().isEmpty()){
              d.setRg("Não Preenchido");
        }else{
              d.setRg(rg.getText());
        }
        if(ctps.getText().isEmpty()){
              d.setCtps("Não Preenchido");
        }else{
              d.setCtps(ctps.getText());
        }
        if(serie.getText().isEmpty()){
              d.setSerie("Não Preenchido");
        }else{
              d.setSerie(serie.getText());
        }
        if(uf.getText().isEmpty()){
              d.setUf("Não Preenchido");
        }else{
              d.setUf(uf.getText());
        }
        
         if(dt.getText().isEmpty()){
              d.setDt_ctps("Não Preenchido");
        }else{
              d.setDt_ctps(dt.getText());
        }
        
         if(pis.getText().isEmpty()){
              d.setPis("Não Preenchido");
        }else{
              d.setPis(pis.getText());
        }
         if(dtPis.getText().isEmpty()){
              d.setDt_pis("Não Preenchido");
        }else{
              d.setDt_pis(dt.getText());
        }
        
        if(dtPis.getText().isEmpty()){
              d.setDt_pis("Não Preenchido");
        }else{
              d.setDt_pis(dt.getText());
        }
        if(dtPis.getText().isEmpty()){
              d.setDt_pis("Não Preenchido");
        }else{
              d.setDt_pis(dt.getText());
        }
        if(agencia.getText().isEmpty()){
              d.setConta_ag("Não Preenchido");
        }else{
              d.setConta_ag(agencia.getText());
        }
         
        if(digito.getText().isEmpty()){
              d.setConta_digito("Não Preenchido");
        }else{
              d.setConta_digito(digito.getText());
        }
        
        
       

     PDDocument document = new PDDocument();
           PDPage page = new PDPage();
     
        try {
            
           
           document.addPage(page);
      //Retrieving the pages of the document 
      
      
     
       
      //creating the PDPageContentStream object
      PDPageContentStream contents = new PDPageContentStream(document, page);

      //Drawing the image in the PDF document
      
      
      //Closing the PDPageContentStream object
      contents.close();		
      
        PDPageContentStream contentStream = new PDPageContentStream(document, page);
      contentStream.beginText(); 
      
      contentStream.setFont(PDType1Font.TIMES_ROMAN, 12);
      contentStream.setLeading(14.5f);

      //Setting the position for the line
      contentStream.newLineAtOffset(25, 725);     
      String text = "Ficha de Cobertura";
      contentStream.showText(text);
      contentStream.newLine();
      contentStream.newLine();
      contentStream.showText("     Dados Pessoais:"); 
      contentStream.newLine();
      contentStream.newLine();
      contentStream.showText("Nome da Cobertura:  " + nome.getText());  
      contentStream.newLine();
      contentStream.showText("Data de Nascimento:  " + dtNasc.getText());  
      contentStream.newLine();
      
      if (end.getText().isEmpty()){
          contentStream.showText("Endereço: Não Cadastrado" );  
      }else{
          
          
          
          contentStream.showText("Endereço:  " + end.getText());
          contentStream.showText("   " + "Nº:  " + endNum.getText());
          contentStream.newLine();
          contentStream.showText("Bairro:  " + bairro.getText());
          contentStream.showText("   " + "Cidade:  " + cidade.getText());
          contentStream.showText("   " + "CEP:  " + cep.getText());
          contentStream.showText("   " + "Cidade Nat:  " + cidadeNat.getText());
      }
      
       contentStream.newLine();
      
      if (nmPai.getText().isEmpty()){
          contentStream.showText("Nome do Pai: Não Cadastrado" );  
      }else{
          contentStream.showText("Nome do Pai:   " + nmPai.getText() );  
         
      }
      
       contentStream.newLine();
      
      if (nmMae.getText().isEmpty()){
          contentStream.showText("Nome da Mãe: Não Cadastrado" );  
      }else{
          contentStream.showText("Nome da Mãe:   " + nmMae.getText() );  
         
      }
      
      contentStream.newLine();
      contentStream.newLine();
      contentStream.showText("     Dados Para Contato:"); 
      contentStream.newLine();
      contentStream.newLine();
      
      
      if (fone.getText().isEmpty()){
          contentStream.showText("Telefone: Não Cadastrado" );  
      }else{
          contentStream.showText("Telefone:   " + fone.getText() );  
         
      }
      
        contentStream.newLine();
      
      if (celular.getText().isEmpty()){
          contentStream.showText("Celular: Não Cadastrado" );  
      }else{
          contentStream.showText("Celular:   " + celular.getText() );  
         
      }
      
      contentStream.newLine();
      contentStream.newLine();
      contentStream.showText("     Documentos:"); 
      contentStream.newLine();
      contentStream.newLine();
     
      
      if (cpf.getText().isEmpty()){
          contentStream.showText("CPF: Não Cadastrado" );  
      }else{
          contentStream.showText("CPF:   " + cpf.getText() );  
         
      }
      
      if (rg.getText().isEmpty()){
          contentStream.showText("   " + "RG: Não Cadastrado" );  
      }else{
          contentStream.showText("   " +  "RG:   " + rg.getText() );  
         
      }
      
         contentStream.newLine();
      
      if (ctps.getText().isEmpty()){
          contentStream.showText("CTPS: Não Cadastrado" );  
      }else{
          contentStream.showText("CTPS:   " + ctps.getText() );
          contentStream.showText("   " +  "Serie:   " + serie.getText() ); 
          contentStream.showText("   " +  "UF:   " + uf.getText() ); 
          contentStream.showText("   " +  "DT:   " + dt.getText() ); 
         
      }
      
       contentStream.newLine();
       
      if (pis.getText().isEmpty()){
          contentStream.showText("PIS: Não Cadastrado" );  
      }else{
          contentStream.showText("PIS:   " + pis.getText() );  
          contentStream.showText("   " +  "DT:   " + dtPis.getText() );
      }
           
      
      
      contentStream.newLine();
      contentStream.newLine();
      contentStream.showText("     Dados Bancario:"); 
      contentStream.newLine();
      contentStream.newLine();
     
      contentStream.showText("Banco:   " + tipoConta.getSelectedItem() );
      contentStream.newLine();
      contentStream.showText("Agencia:   " + agencia.getText() );
      contentStream.showText("   " + "Digito:   " +  digito.getText() );
      
      contentStream.newLine();
       
      if (cc.isSelected()){
            contentStream.showText("Conta Corrente:   " + numCC.getText() );  
      }else{ 
          contentStream.showText("Conta Corrente: Não Cadastrado" );
      }
      
      contentStream.newLine();
      
      if (cp.isSelected()){
            contentStream.showText("Conta Poupança:   " + numCP.getText() );  
      }else{ 
          contentStream.showText("Conta Poupança: Não Cadastrado" );
      }
      
      
      
      
       contentStream.endText();
      


      contentStream.close();

   File file = new File("PDF/");
   
     if (file.exists()) {
            
          document.save(new File("PDF/" + nome.getText()+".pdf"));
            
        }else{
            
         
            new File("PDF/").mkdir();
              document.save(new File("PDF/" + nome.getText()+".pdf"));
            
        }
      

      //Closing the document
      document.close();
        } catch (IOException ex) {
            Logger.getLogger(CadastroCobertura.class.getName()).log(Level.SEVERE, null, ex);
        }
      

   
         
      
        


 

        
        
        
        d.setBanco(tipoConta.getSelectedItem().toString());
        
        
        if(cc.isSelected()){
            d.setN_conta(numCC.getText());
        }else{
            d.setN_conta("NULO");
        }
        if(cp.isSelected()){
            d.setN_conta_poup(numCP.getText());
        }else{
            d.setN_conta_poup("NULO");
        }
        
         if(nome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Insira o Nome", "Error", JOptionPane.WARNING_MESSAGE);
            
            
        }else{
            dao.insertCobertura(d);
        }   
        
        
        
        nome.setText("");
        end.setText("");
        endNum.setText("");
        bairro.setText("");
        cidade.setText("");
        cep.setText("");
        cidadeNat.setText("");
        fone.setText("");
        celular.setText("");
        dtNasc.setText("");
        nmPai.setText("");
        nmMae.setText("");
        
        cpf.setText("");
        rg.setText("");
        ctps.setText("");
        serie.setText("");
        uf.setText("");
        dt.setText("");
        pis.setText("");
        dtPis.setText("");

        
        agencia.setText("");
        digito.setText("");
        
        numCC.setText("");
        numCP.setText("");
    }//GEN-LAST:event_cadCobActionPerformed

    private void limpDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpDadosActionPerformed
        // TODO add your handling code here:
         nome.setText("");
        end.setText("");
        endNum.setText("");
        bairro.setText("");
        cidade.setText("");
        cep.setText("");
        cidadeNat.setText("");
        fone.setText("");
        celular.setText("");
        dtNasc.setText("");
        nmPai.setText("");
        nmMae.setText("");
        
        cpf.setText("");
        rg.setText("");
        ctps.setText("");
        serie.setText("");
        uf.setText("");
        dt.setText("");
        pis.setText("");
        dtPis.setText("");

        
        agencia.setText("");
        digito.setText("");
        
        numCC.setText("");
        numCP.setText("");
    }//GEN-LAST:event_limpDadosActionPerformed

    private void tipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoContaActionPerformed

    private void btFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFichasActionPerformed
        // TODO add your handling code here:

        Coberturas tabCober = new Coberturas();

        tabCober.setVisible(true);
    }//GEN-LAST:event_btFichasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCobertura().setVisible(true);
            }
        });
    }
    
    private void setMask() {
        try {
            
            MaskFormatter maskCelular = new MaskFormatter("(##) #####-####");
            celular.setFormatterFactory(new DefaultFormatterFactory(maskCelular, maskCelular));
            
            MaskFormatter mask = new MaskFormatter("(##) #####-###");
            fone.setFormatterFactory(new DefaultFormatterFactory(mask, mask));
            
            MaskFormatter maskNas = new MaskFormatter("##/##/####");
            dtNasc.setFormatterFactory(new DefaultFormatterFactory(maskNas, maskNas));
            
            MaskFormatter maskCEP = new MaskFormatter("#####-###");
            cep.setFormatterFactory(new DefaultFormatterFactory(maskCEP, maskCEP));
            
            MaskFormatter maskDT = new MaskFormatter("##/##/####");
            dt.setFormatterFactory(new DefaultFormatterFactory(maskDT, maskDT));
            
            MaskFormatter maskDTPIS = new MaskFormatter("##/##/####");
            dtPis.setFormatterFactory(new DefaultFormatterFactory(maskDTPIS, maskDTPIS));
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agencia;
    private javax.swing.JTextField bairro;
    private javax.swing.JButton btFichas;
    private javax.swing.JButton cadCob;
    private javax.swing.JCheckBox cc;
    private javax.swing.JFormattedTextField celular;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cidadeNat;
    private javax.swing.JPanel conta;
    private javax.swing.JCheckBox cp;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField ctps;
    private javax.swing.JPanel dadosPessoais;
    private javax.swing.JTextField digito;
    private javax.swing.JPanel documentos;
    private javax.swing.JFormattedTextField dt;
    private javax.swing.JFormattedTextField dtNasc;
    private javax.swing.JFormattedTextField dtPis;
    private javax.swing.JTextField end;
    private javax.swing.JTextField endNum;
    private javax.swing.JFormattedTextField fone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpDados;
    private javax.swing.JTextField nmMae;
    private javax.swing.JTextField nmPai;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numCC;
    private javax.swing.JTextField numCP;
    private javax.swing.JTextField pis;
    private javax.swing.JTextField rg;
    private javax.swing.JTextField serie;
    private javax.swing.JComboBox<String> tipoConta;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables
}
