/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.Query;
import Model.Funcionarios;
import java.awt.Font;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author mauri
 */
public class Copeiras extends javax.swing.JFrame {
List<Funcionarios> listafuncionario = new ArrayList<Funcionarios>();
    /**
     * Creates new form Copeiras
     */
    public Copeiras() {
        initComponents();
        btDelete.setEnabled(false);
        btSalvarDados.setEnabled(false);
        setMask();
        Font font = new Font("Arial",Font.PLAIN,20);
        telefone.setFont(font);
        DefaultTableModel modelo = (DefaultTableModel) tabelaCop.getModel();
        this.listafuncionario= new Query().selectCop();
        readtabela();
        
    }
    
     private void setMask() {
        try {
            MaskFormatter mask = new MaskFormatter("(##) #####-####");
            telefone.setFormatterFactory(new DefaultFormatterFactory(mask, mask));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }
    
    
    public void readtabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCop.getModel();
        modelo.setNumRows(0);
        Query ddao = new Query();

        for (Funcionarios d : listafuncionario) {

            modelo.addRow(new Object[]{
               
               
               d.getPrefixo_agencia(),
               d.getNome_agencia(),
               d.getNome_funcionario(),
               d.getTelefone_funcionario(),
               d.getRoupa(),
               d.getCargo_agencia(),
               d.getId()
               
               
            });

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        prefixo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        agencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        funcionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        roupa = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        btSalvarDados = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        searchPr = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();
        telefone = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCop = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 720));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 3, 36)); // NOI18N
        jLabel1.setText("Copeiras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(573, 573, 573)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Prefixo da Agencia:");

        prefixo.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Nome da Agencia:");

        agencia.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Nome do Funcionario:");

        funcionario.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel6.setText("Telefone:");

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel7.setText("Tamanho da Roupa:");

        roupa.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        roupa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "M", "G", "GG", "EXG" }));
        roupa.setAlignmentX(1.0F);
        roupa.setAlignmentY(1.0F);

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel8.setText("Cargo:");

        cargo.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Copeira", "Telefonista", "Limpeza" }));
        cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel2.setText("ID:");

        ID.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N

        btSalvarDados.setText("Salvar Dados Atualizados");
        btSalvarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarDadosActionPerformed(evt);
            }
        });

        btDelete.setText("Deletar Dados Salvos");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel9.setText("Procurar Prefixo:");

        searchPr.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        searchPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPrActionPerformed(evt);
            }
        });

        btSearch.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        btSearch.setText("Procurar");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(521, 521, 521)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btSalvarDados)
                        .addGap(66, 66, 66)
                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchPr, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btSearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57)
                        .addComponent(prefixo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addComponent(agencia, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(24, 24, 24)
                                .addComponent(funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(44, 44, 44)
                                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(577, 577, 577)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(48, 48, 48)
                                .addComponent(roupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prefixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(roupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(searchPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSearch))
                    .addComponent(btSalvarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabelaCop.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        tabelaCop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Prefixo", "Agencia", "Funcionario", "Telefone", "Roupa", "Cargo", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCop.setRowHeight(22);
        tabelaCop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaCopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCopMouseClicked
        // TODO add your handling code here:
        btDelete.setEnabled(true);
        btSalvarDados.setEnabled(true);
        int registro = tabelaCop.getSelectedRow();
        
        ID.setText(tabelaCop.getValueAt(tabelaCop.getSelectedRow(), 6).toString());
        prefixo.setText(tabelaCop.getValueAt(tabelaCop.getSelectedRow(), 0).toString());
        agencia.setText(tabelaCop.getValueAt(tabelaCop.getSelectedRow(), 1).toString());
        funcionario.setText(tabelaCop.getValueAt(tabelaCop.getSelectedRow(), 2).toString());
        telefone.setText(tabelaCop.getValueAt(tabelaCop.getSelectedRow(), 3).toString());
        roupa.setSelectedItem(tabelaCop.getValueAt(tabelaCop.getSelectedRow(), 4).toString());
        cargo.setSelectedItem(tabelaCop.getValueAt(tabelaCop.getSelectedRow(), 5).toString());

    }//GEN-LAST:event_tabelaCopMouseClicked

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        // TODO add your handling code here:

        Funcionarios d = new Funcionarios();

        Query dao = new Query();

        String nulo;
        nulo = searchPr.getText();

        if (nulo.isEmpty()) {

            DefaultTableModel modelo = (DefaultTableModel) tabelaCop.getModel();
            this.listafuncionario= new Query().selectCop();
            readtabela();

        } else {

            d.setPrefixo_agencia(Integer.parseInt(searchPr.getText()));

            dao.selectTelFilter(d);

            DefaultTableModel modelo = (DefaultTableModel) tabelaCop.getModel();
            this.listafuncionario= new Query().selectCopFilter(d);
            readtabela();
        }
    }//GEN-LAST:event_btSearchActionPerformed

    private void searchPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPrActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:

        Funcionarios d = new Funcionarios();

        Query dao = new Query();

        d.setId(ID.getText());
        dao.delete(d);

        DefaultTableModel modelo = (DefaultTableModel) tabelaCop.getModel();
        this.listafuncionario = new Query().selectTel();
        readtabela();

        ID.setText("");
        agencia.setText("");
        funcionario.setText("");
        telefone.setText("");
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btSalvarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarDadosActionPerformed
        // TODO add your handling code here:

        Funcionarios d = new Funcionarios();

        Query dao = new Query();

        d.setPrefixo_agencia(Integer.parseInt(prefixo.getText()));
        d.setNome_agencia(agencia.getText());
        d.setNome_funcionario(funcionario.getText());
        d.setTelefone_funcionario(telefone.getText());
        d.setCargo_agencia(cargo.getSelectedItem().toString());
        d.setRoupa(roupa.getSelectedItem().toString());
        d.setBota(0);
        d.setId(ID.getText());

        ID.setText("");
        prefixo.setText("");
        agencia.setText("");
        funcionario.setText("");
        telefone.setText("");

        dao.update(d);

        DefaultTableModel modelo = (DefaultTableModel) tabelaCop.getModel();
        this.listafuncionario= new Query().selectTel();
        readtabela();
    }//GEN-LAST:event_btSalvarDadosActionPerformed

    private void cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Copeiras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Copeiras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Copeiras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Copeiras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Copeiras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JTextField agencia;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSalvarDados;
    private javax.swing.JButton btSearch;
    private javax.swing.JComboBox<String> cargo;
    private javax.swing.JTextField funcionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField prefixo;
    private javax.swing.JComboBox<String> roupa;
    private javax.swing.JTextField searchPr;
    private javax.swing.JTable tabelaCop;
    private javax.swing.JFormattedTextField telefone;
    // End of variables declaration//GEN-END:variables
}
